#!/bin/bash

# Set the working directory to the root of the repository
cd /home/jovyan/Speech-Recognition-Exercise

# Generate the 'configure' script from 'configure.in'
autoreconf -fiv

# Install necessary build dependencies
apt-get update && \
    apt-get install -y autoconf automake libtool libsndfile1-dev

# Configure and build PortAudio
./configure && \
    make && \
    make install
