#!/bin/bash

# Copy the tar file to the desired directory
COPY pa_stable_v190700_20210406.tar /home/$NB_USER/

# Extract the contents of the tar file directly into the desired directory
RUN tar -xf /home/$NB_USER/pa_stable_v190700_20210406.tar -C /home/$NB_USER/ && \
    rm /home/$NB_USER/pa_stable_v190700_20210406.tar

# Set the working directory to the PortAudio source directory
WORKDIR /home/$NB_USER/portaudio

# Generate the 'configure' script from 'configure.in'
RUN autoreconf -fiv

# Install necessary build dependencies
RUN apt-get update && \
    apt-get install -y autoconf automake libtool libsndfile1-dev

# Configure and build PortAudio
RUN ./configure && \
    make && \
    make install

# Set the working directory back to the home directory
WORKDIR /home/$NB_USER

# Copy the Jupyter notebook to the home directory
COPY Speech_Recognition_Exercise.ipynb /home/$NB_USER/

# Set permissions for the notebook
# RUN chown $NB_USER:users /home/$NB_USER/Speech_Recognition_Exercise.ipynb
# RUN chmod 664 /home/$NB_USER/Speech_Recognition_Exercise.ipynb

# Install Python dependencies
RUN pip install -r requirements.txt

# Start the Jupyter Lab
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--no-browser", "--allow-root"]
