#!/bin/bash

# Copy the entire repository to the home directory
COPY . /home/$NB_USER/

# Set the working directory to the root of the repository
WORKDIR /home/$NB_USER

# Generate the 'configure' script from 'configure.in'
RUN autoreconf -fiv

# Install necessary build dependencies
RUN apt-get update && \
    apt-get install -y autoconf automake libtool libsndfile1-dev

# Configure and build PortAudio
RUN ./configure && \
    make && \
    make install

# Set the working directory back to the home directory
WORKDIR /home/$NB_USER

# Copy the Jupyter notebook to the home directory
COPY Speech_Recognition_Exercise.ipynb /home/$NB_USER/

